### PR TITLE
Feature/letsencrypt certificates

### PR DESCRIPTION
**Pull request by aeden**
Implement Let's Encrypt purchase and renew API endpoint consumers.

### CODE REVIEW

**Comment by weppos** [comment]
@aeden as for the other PR, this is ready for review now, but I can't assign you as reviewer as you opened it.

**Comment by aeden** [comment]
@weppos did you want to include the issue endpoints?

**Comment by weppos** [comment]
I did, yes. I'm pretty sure I created them, but I can't find them here. Let me check if I forgot to push a commit.

**Comment by weppos** [comment]
@aeden I added the missing methods

**Pull request merged**
