### PR TITLE
Migrate project to Gradle and set a modern Java compatibility level

### PR DESCRIPTION
**Pull request by ggalmazor**
This PR migrates this project to Gradle and sets the source and target's compatibility level to Java 11, which is the current LTS version.

This PR also takes care of the dependabot configuration and the CI process.

The only part that's missing from this PR would be anything related to the publication of this library in public artifact repositories such as the Sonatype OSS Maven repo.

### CODE REVIEW

**Comment by weppos** [comment]
> The only part that's missing from this PR would be anything related to the publication of this library in public artifact repositories such as the Sonatype OSS Maven repo.

What's the plan to address this step? Is it possible to publish to OSS Maven repo from Gradle?

**Comment by ggalmazor** [comment]
> > The only part that's missing from this PR would be anything related to the publication of this library in public artifact repositories such as the Sonatype OSS Maven repo.
> 
> What's the plan to address this step? Is it possible to publish to OSS Maven repo from Gradle?

Yes, there's full support for that through plugins. 

My plan was to get 2 reviews before asking you for help with this either to configure a plugin to push the JAR to Sonatype's repo for OSS projects or evaluate alternative repos with a lighter approach. I've already started evaluating JitPack, GitHub Archive, and JBoss

**Comment by ggalmazor** [comment]
I've updated the `CONTRIBUTING.md` file. I have removed the Release > Configuring section because we need to figure out how to do the release in Gradle first.

**Comment by ggalmazor** [comment]
Both official guides from OSSRH and Gradle are informative, but also contradicting and a general mess, as always :\

Will follow https://dev.to/kengotoda/deploying-to-ossrh-with-gradle-in-2020-1lhi to configure the release task

**Comment by ggalmazor** [comment]
I've live reviewed the PR both with @san983 and @sbastn, and I've also tested locally the Maven publisher tasks, so I'm going to merge this PR first thing tomorrow to be able to focus on breaking code changes for https://github.com/dnsimple/dnsimple-java/milestone/1

**Comment by ggalmazor** [comment]
Just tested the publish to the (staging) repo for Maven and it worked.

**Pull request merged**
